###################### LISTA POSSIBILI COMANDI VIA SMS

ADAPTIVE_GDPR NOME COGNOME NUMERO_TELEFONO
RISPOSTA: ACCETTO (conferma consenso) OPPURE IGNORARE (scade dopo 35min)

ADAPTIVE_PROFILE NOME COGNOME NUMERO_TELEFONO VIN
RISPOSTA: NESSUNA (registrazione automatica finestra 24 ore)

STOP
RISPOSTA: NESSUNA (revoca consensi accettati O richieste pendenti)

###################### VARIABILI

@api_key = 272f8ccd
@api_secret = 57AZHUDdxtgK55GT
@cellulare_operativo_autorizzato = 447441446357
@numero_vonage_datapolar = 447441446357
@messaggio_adaptive_gdpr = ADAPTIVE_GDPR Tedesco Davide 447441446357
@messaggio_adaptive_profile = ADAPTIVE_PROFILE Tedesco Davide 447441446357 5YJ3000000NEXUS01

###################### INVIO SMS REALI TRAMITE VONAGE API

### Invia SMS ADAPTIVE_GDPR
POST https://rest.nexmo.com/sms/json
Content-Type: application/x-www-form-urlencoded

from={{numero_vonage_datapolar}}&to={{cellulare_operativo_autorizzato}}&text={{messaggio_adaptive_gdpr}}&api_key={{api_key}}&api_secret={{api_secret}}

### Invia SMS ADAPTIVE_PROFILE
POST https://rest.nexmo.com/sms/json
Content-Type: application/x-www-form-urlencoded

from={{numero_vonage_datapolar}}&to={{cellulare_operativo_autorizzato}}&text={{messaggio_adaptive_profile}}&api_key={{api_key}}&api_secret={{api_secret}}

###################### TEST PER SIMULARE CHIAMATE VONAGE AL WEBHOOK ( SIMULAZIONE )

### TEST ADAPTIVE_GDPR
POST https://dev-api.datapolar.dev/api/Sms/webhook
Content-Type: application/x-www-form-urlencoded

msisdn={{cellulare_operativo_autorizzato}}&to={{numero_vonage_datapolar}}&text={{messaggio_adaptive_gdpr}}

### Test ACCETTO
POST https://dev-api.datapolar.dev/api/Sms/webhook
Content-Type: application/x-www-form-urlencoded

msisdn={{cellulare_operativo_autorizzato}}&to={{numero_vonage_datapolar}}&text=ACCETTO

### Test STOP
POST https://dev-api.datapolar.dev/api/Sms/webhook
Content-Type: application/x-www-form-urlencoded

msisdn={{cellulare_operativo_autorizzato}}&to={{numero_vonage_datapolar}}&text=STOP

### Test ADAPTIVE_PROFILE
POST https://dev-api.datapolar.dev/api/Sms/webhook
Content-Type: application/x-www-form-urlencoded

msisdn={{cellulare_operativo_autorizzato}}&to={{numero_vonage_datapolar}}&text={{messaggio_adaptive_profile}}