// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolarDrive.Data.DbContexts;

#nullable disable

namespace PolarDrive.Data.Migrations
{
    [DbContext(typeof(PolarDriveDbContext))]
    [Migration("20250503122425_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PolarDrive.Data.Entities.AnonymizedTeslaVehicleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnonymizedJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginalDataId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeslaVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginalDataId")
                        .IsUnique();

                    b.HasIndex("TeslaVehicleId");

                    b.ToTable("AnonymizedTeslaVehicleData");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.ClientCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LandlineNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PecAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferentEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferentMobileNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferentPecAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PecAddress")
                        .IsUnique();

                    b.HasIndex("VatNumber")
                        .IsUnique();

                    b.ToTable("ClientCompanies");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.ClientConsent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeslaVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.HasIndex("TeslaVehicleId");

                    b.ToTable("ClientConsents");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.ClientTeslaToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeslaVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeslaVehicleId")
                        .IsUnique();

                    b.HasIndex("TeslaVehicleId", "AccessTokenExpiresAt");

                    b.ToTable("ClientTeslaTokens");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.ClientTeslaVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstActivationAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFetchingDataFlag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDeactivationAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFetchingDataAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trim")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("ClientTeslaVehicles");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.DemoSmsEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeslaVehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeslaVehicleId");

                    b.ToTable("DemoSmsEvents");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.OutagePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoDetected")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OutageEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OutageStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeslaVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipFilePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.HasIndex("TeslaVehicleId");

                    b.ToTable("OutagePeriods");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.PdfReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyVatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleVin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PdfReports");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.TeslaVehicleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeslaVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeslaVehicleId");

                    b.ToTable("TeslaVehicleData");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.TeslaWorkflow", b =>
                {
                    b.Property<int>("TeslaVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActiveFlag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFetchingDataFlag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastStatusChangeAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TeslaVehicleId");

                    b.ToTable("TeslaWorkflows");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.TeslaWorkflowEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldChanged")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NewValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OldValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeslaVehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeslaVehicleId");

                    b.ToTable("TeslaWorkflowEvents");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.AnonymizedTeslaVehicleData", b =>
                {
                    b.HasOne("PolarDrive.Data.Entities.TeslaVehicleData", "OriginalData")
                        .WithMany()
                        .HasForeignKey("OriginalDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolarDrive.Data.Entities.ClientTeslaVehicle", "ClientTeslaVehicle")
                        .WithMany()
                        .HasForeignKey("TeslaVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTeslaVehicle");

                    b.Navigation("OriginalData");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.ClientConsent", b =>
                {
                    b.HasOne("PolarDrive.Data.Entities.ClientCompany", "ClientCompany")
                        .WithMany()
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolarDrive.Data.Entities.ClientTeslaVehicle", "ClientTeslaVehicle")
                        .WithMany()
                        .HasForeignKey("TeslaVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");

                    b.Navigation("ClientTeslaVehicle");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.ClientTeslaToken", b =>
                {
                    b.HasOne("PolarDrive.Data.Entities.ClientTeslaVehicle", "ClientTeslaVehicle")
                        .WithOne()
                        .HasForeignKey("PolarDrive.Data.Entities.ClientTeslaToken", "TeslaVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTeslaVehicle");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.ClientTeslaVehicle", b =>
                {
                    b.HasOne("PolarDrive.Data.Entities.ClientCompany", "ClientCompany")
                        .WithMany()
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.DemoSmsEvent", b =>
                {
                    b.HasOne("PolarDrive.Data.Entities.ClientTeslaVehicle", "ClientTeslaVehicle")
                        .WithMany()
                        .HasForeignKey("TeslaVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTeslaVehicle");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.OutagePeriod", b =>
                {
                    b.HasOne("PolarDrive.Data.Entities.ClientCompany", "ClientCompany")
                        .WithMany()
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PolarDrive.Data.Entities.ClientTeslaVehicle", "ClientTeslaVehicle")
                        .WithMany()
                        .HasForeignKey("TeslaVehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientCompany");

                    b.Navigation("ClientTeslaVehicle");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.TeslaVehicleData", b =>
                {
                    b.HasOne("PolarDrive.Data.Entities.ClientTeslaVehicle", "ClientTeslaVehicle")
                        .WithMany()
                        .HasForeignKey("TeslaVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTeslaVehicle");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.TeslaWorkflow", b =>
                {
                    b.HasOne("PolarDrive.Data.Entities.ClientTeslaVehicle", "ClientTeslaVehicle")
                        .WithOne()
                        .HasForeignKey("PolarDrive.Data.Entities.TeslaWorkflow", "TeslaVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTeslaVehicle");
                });

            modelBuilder.Entity("PolarDrive.Data.Entities.TeslaWorkflowEvent", b =>
                {
                    b.HasOne("PolarDrive.Data.Entities.ClientTeslaVehicle", "ClientTeslaVehicle")
                        .WithMany()
                        .HasForeignKey("TeslaVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTeslaVehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
