import { NextApiRequest, NextApiResponse } from "next";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json([
    {
      companyVatNumber: "63123456789",
      companyName: "Paninoteca Rossi S.r.l.",
      email: "info@paninotecarossi.it",
      model: "Model 3",
      teslaVehicleVIN: "5YJ3E1EA7KF317001",
      uploadDate: "2024-03-12",
      pdfFilePath: "/pdfs/consents/consent_paninoteca_rossi.pdf",
      accessToken: "mock-access-token-1",
      refreshToken: "mock-refresh-token-1",
      isTeslaActive: true,
      isTeslaFetchingData: true,
    },
    {
      companyVatNumber: "78987654321",
      companyName: "Studio Legale Verdi",
      email: "contatti@studioverdi.it",
      model: "Model S",
      teslaVehicleVIN: "5YJSA1E26HF000101",
      uploadDate: "2024-03-15",
      pdfFilePath: "/pdfs/consents/consent_studio_legale_verdi.pdf",
      accessToken: "mock-access-token-2",
      refreshToken: "mock-refresh-token-2",
      isTeslaActive: false,
      isTeslaFetchingData: true,
    },
    {
      companyVatNumber: "44543216789",
      companyName: "TechZone S.p.A.",
      email: "support@techzone.it",
      model: "Model X",
      teslaVehicleVIN: "5YJXCDE45GF011123",
      uploadDate: "2024-03-20",
      pdfFilePath: "/pdfs/consents/consent_techzone.pdf",
      accessToken: "mock-access-token-3",
      refreshToken: "mock-refresh-token-3",
      isTeslaActive: false,
      isTeslaFetchingData: false,
    },
    {
      companyVatNumber: "56135792468",
      companyName: "Farmacia Centrale S.n.c.",
      email: "info@farmaciacentrale.it",
      model: "Model 3",
      teslaVehicleVIN: "5YJYGDEE0MF005555",
      uploadDate: "2024-03-25",
      pdfFilePath: "/pdfs/consents/consent_farmacia_centrale.pdf",
      accessToken: "mock-access-token-4",
      refreshToken: "mock-refresh-token-4",
      isTeslaActive: true,
      isTeslaFetchingData: true,
    },
    {
      companyVatNumber: "75112358132",
      companyName: "Alfa Costruzioni S.r.l.",
      email: "segreteria@alfacostruzioni.it",
      model: "Model Y",
      teslaVehicleVIN: "7SAYGDEE9PF123999",
      uploadDate: "2024-03-28",
      pdfFilePath: "/pdfs/consents/consent_alfa_costruzioni.pdf",
      accessToken: "mock-access-token-5",
      refreshToken: "mock-refresh-token-5",
      isTeslaActive: true,
      isTeslaFetchingData: true,
    },
    {
      companyVatNumber: "72192837465",
      companyName: "Gamma Energia s.n.c.",
      email: "contatti@gammaenergia.it",
      model: "Model Y",
      teslaVehicleVIN: "5YJ3E1EA2HF001234",
      uploadDate: "2024-04-01",
      pdfFilePath: "/pdfs/consents/consent_gamma_energia.pdf",
      accessToken: "mock-access-token-6",
      refreshToken: "mock-refresh-token-6",
      isTeslaActive: true,
      isTeslaFetchingData: true,
    },
    {
      companyVatNumber: "92314159265",
      companyName: "Studio Architetti Bassi e Longhi",
      email: "info@bassilonghi.it",
      model: "Model 3",
      teslaVehicleVIN: "5YJSA1E20FF000777",
      uploadDate: "2024-04-02",
      pdfFilePath: "/pdfs/consents/consent_studio_bassi_longhi.pdf",
      accessToken: "mock-access-token-7",
      refreshToken: "mock-refresh-token-7",
      isTeslaActive: true,
      isTeslaFetchingData: true,
    },
    {
      companyVatNumber: "82010203040",
      companyName: "Bottega del Caffè di Mario e C.",
      email: "bottega@marioecaffe.it",
      model: "Model S",
      teslaVehicleVIN: "LRWYGDEE7PC888888",
      uploadDate: "2024-04-04",
      pdfFilePath: "/pdfs/consents/consent_bottega_mario.pdf",
      accessToken: "mock-access-token-8",
      refreshToken: "mock-refresh-token-8",
      isTeslaActive: true,
      isTeslaFetchingData: true,
    },
    {
      companyVatNumber: "46001100110",
      companyName: "NextData Analytics S.r.l.",
      email: "contact@nextdata.it",
      model: "Model Y",
      teslaVehicleVIN: "5YJXCDE23JF055432",
      uploadDate: "2024-04-06",
      pdfFilePath: "/pdfs/consents/consent_nextdata.pdf",
      accessToken: "mock-access-token-9",
      refreshToken: "mock-refresh-token-9",
      isTeslaActive: true,
      isTeslaFetchingData: true,
    },
    {
      companyVatNumber: "83999888776",
      companyName: "Autofficina Turbo S.a.s.",
      email: "turbo@autofficina.it",
      model: "Model X",
      teslaVehicleVIN: "5YJSA1E26HF000101",
      uploadDate: "2024-04-08",
      pdfFilePath: "/pdfs/consents/consent_autofficina_turbo.pdf",
      accessToken: "mock-access-token-10",
      refreshToken: "mock-refresh-token-10",
      isTeslaActive: true,
      isTeslaFetchingData: true,
    },
  ]);
}
