import { NextApiRequest, NextApiResponse } from "next";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json([
    {
      id: 1,
      companyVatNumber: "63123456789",
      name: "Paninoteca Rossi S.r.l.",
      address: "Via dei Panini 42, Milano",
      email: "info@paninotecarossi.it",
      pecAddress: "pec@paninotecarossi.it",
      landlineNumber: "02123456788",
      referentName: "Luca Rossi",
      referentMobileNumber: "3201234567",
      referentEmail: "luca@paninotecarossi.it",
      referentPecAddress: "",
    },
    {
      id: 2,
      companyVatNumber: "78987654321",
      name: "Studio Legale Verdi",
      address: "Corso Venezia 12, Roma",
      email: "contatti@studioverdi.it",
      pecAddress: "studioverdi@pec.it",
      landlineNumber: "06445566714",
      referentName: "Chiara Verdi",
      referentMobileNumber: "3471122334",
      referentEmail: "chiara.verdi@studioverdi.it",
      referentPecAddress: "c.verdi@pec.studioverdi.it",
    },
    {
      id: 3,
      companyVatNumber: "44543216789",
      name: "TechZone S.p.A.",
      address: "Viale Innovazione 8, Torino",
      email: "support@techzone.it",
      pecAddress: "pec@techzone.it",
      landlineNumber: "01177889904",
      referentName: "Marco Bianchi",
      referentMobileNumber: "3359988776",
      referentEmail: "marco.b@techzone.it",
      referentPecAddress: "m.bianchi@pec.techzone.it",
    },
    {
      id: 4,
      companyVatNumber: "56135792468",
      name: "Farmacia Centrale S.n.c.",
      address: "Piazza della Salute 2, Firenze",
      email: "info@farmaciacentrale.it",
      pecAddress: "farmaciacentrale@pec.it",
      landlineNumber: "05522334456",
      referentName: "Giulia Neri",
      referentMobileNumber: "3281239874",
      referentEmail: "g.neri@farmaciacentrale.it",
      referentPecAddress: "giulia.neri@pec.farmacia.it",
    },
    {
      id: 5,
      companyVatNumber: "75112358132",
      name: "Alfa Costruzioni S.r.l.",
      address: "Via del Mattone 100, Bologna",
      email: "segreteria@alfacostruzioni.it",
      pecAddress: "pec@alfacostruzioni.it",
      landlineNumber: "05199887783",
      referentName: "Federico Costa",
      referentMobileNumber: "3294455667",
      referentEmail: "f.costa@alfacostruzioni.it",
      referentPecAddress: "federico.costa@pec.alfacostruzioni.it",
    },
    {
      id: 6,
      companyVatNumber: "72192837465",
      name: "Gamma Energia s.n.c.",
      address: "Via Solare 15, Napoli",
      email: "contatti@gammaenergia.it",
      pecAddress: "pec@gammaenergia.it",
      landlineNumber: "08144556677",
      referentName: "Anna Romano",
      referentMobileNumber: "3402211334",
      referentEmail: "anna@gammaenergia.it",
      referentPecAddress: "a.romano@pec.gammaenergia.it",
    },
    {
      id: 7,
      companyVatNumber: "92314159265",
      name: "Studio Architetti Bassi e Longhi",
      address: "Via Architettura 7, Bari",
      email: "info@bassilonghi.it",
      pecAddress: "pec@bassilonghi.it",
      landlineNumber: "08033221138",
      referentName: "Leonardo Longhi",
      referentMobileNumber: "3387766554",
      referentEmail: "l.longhi@bassilonghi.it",
      referentPecAddress: "leo.longhi@pec.bassilonghi.it",
    },
    {
      id: 8,
      companyVatNumber: "82010203040",
      name: "Bottega del Caffè di Mario e C.",
      address: "Via Cavour 50, Palermo",
      email: "bottega@marioecaffe.it",
      pecAddress: "pec@bottegacaffe.it",
      landlineNumber: "09122334401",
      referentName: "Mario Grillo",
      referentMobileNumber: "3315566778",
      referentEmail: "mario@marioecaffe.it",
      referentPecAddress: "m.grillo@pec.bottegacaffe.it",
    },
    {
      id: 9,
      companyVatNumber: "46001100110",
      name: "NextData Analytics S.r.l.",
      address: "Via Digitale 3, Trento",
      email: "contact@nextdata.it",
      pecAddress: "pec@nextdata.it",
      landlineNumber: "04618877664",
      referentName: "Serena Bellini",
      referentMobileNumber: "3391122445",
      referentEmail: "serena.bellini@nextdata.it",
      referentPecAddress: "s.bellini@pec.nextdata.it",
    },
    {
      id: 10,
      companyVatNumber: "83999888776",
      name: "Autofficina Turbo S.a.s.",
      address: "Via del Motore 21, Genova",
      email: "turbo@autofficina.it",
      pecAddress: "pec@autofficina.it",
      landlineNumber: "01033445577",
      referentName: "Gabriele Ferro",
      referentMobileNumber: "3489988771",
      referentEmail: "g.ferro@autofficina.it",
      referentPecAddress: "gabriele.ferro@pec.autofficina.it",
    },
  ]);
}
