import { NextApiRequest, NextApiResponse } from "next";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json([
    {
      clientCompanyId: 1,
      vin: "5YJ3E1EA7KF317001",
      model: "Model 3",
      trim: "Long Range AWD",
      color: "Pearl White Multi-Coat",
      isActiveFlag: true,
      isFetchingDataFlag: true,
      firstActivationAt: "2023-09-01",
      lastDeactivationAt: null,
      lastFetchingDataAt: null,
    },
    {
      clientCompanyId: 2,
      vin: "5YJSA1E26HF000101",
      model: "Model S",
      trim: "Plaid",
      color: "Solid Black",
      isActiveFlag: true,
      isFetchingDataFlag: true,
      firstActivationAt: "2023-11-15",
      lastDeactivationAt: null,
      lastFetchingDataAt: null,
    },
    {
      clientCompanyId: 3,
      vin: "5YJXCDE45GF011123",
      model: "Model X",
      trim: "Performance",
      color: "Deep Blue Metallic",
      isActive: false,
      firstActivationAt: "2022-03-10",
      lastDeactivationAt: "2024-01-01",
      lastFetchingDataAt: "2024-02-01",
    },
    {
      clientCompanyId: 1,
      vin: "LRW3E7FA1MC123456",
      model: "Model 3",
      trim: "Standard Plus",
      color: "Midnight Silver Metallic",
      isActiveFlag: true,
      isFetchingDataFlag: true,
      firstActivationAt: "2024-02-01",
      lastDeactivationAt: null,
      lastFetchingDataAt: null,
    },
    {
      clientCompanyId: 4,
      vin: "5YJYGDEE0MF005555",
      model: "Model Y",
      trim: "Long Range",
      color: "Red Multi-Coat",
      isActiveFlag: true,
      isFetchingDataFlag: true,
      firstActivationAt: "2023-12-20",
      lastDeactivationAt: null,
      lastFetchingDataAt: null,
    },
    {
      clientCompanyId: 5,
      vin: "7SAYGDEE9PF123999",
      model: "Model Y",
      trim: "Performance",
      color: "Quicksilver",
      isActive: false,
      firstActivationAt: "2022-06-01",
      lastDeactivationAt: "2024-03-01",
      lastFetchingDataAt: null,
    },
    {
      clientCompanyId: 6,
      vin: "5YJ3E1EA2HF001234",
      model: "Model 3",
      trim: "Standard RWD",
      color: "Custom Green Wrap",
      isActiveFlag: true,
      isFetchingDataFlag: true,
      firstActivationAt: "2023-05-05",
      lastDeactivationAt: null,
      lastFetchingDataAt: null,
    },
    {
      clientCompanyId: 7,
      vin: "5YJSA1E20FF000777",
      model: "Model S",
      trim: "Long Range",
      color: "Silver Metallic",
      isActive: false,
      firstActivationAt: "2021-11-10",
      lastDeactivationAt: "2023-10-10",
      lastFetchingDataAt: "2023-12-10",
    },
    {
      clientCompanyId: 8,
      vin: "LRWYGDEE7PC888888",
      model: "Model Y",
      trim: "Rear-Wheel Drive",
      color: "Stealth Grey",
      isActiveFlag: true,
      isFetchingDataFlag: true,
      firstActivationAt: "2024-01-10",
      lastDeactivationAt: null,
      lastFetchingDataAt: null,
    },
    {
      clientCompanyId: 9,
      vin: "5YJXCDE23JF055432",
      model: "Model X",
      trim: "Dual Motor",
      color: "Ultra Red",
      isActiveFlag: true,
      isFetchingDataFlag: true,
      firstActivationAt: "2023-08-15",
      lastDeactivationAt: null,
      lastFetchingDataAt: null,
    },
  ]);
}
